In [452]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as  sm
from sklearn.preprocessing import StandardScaler as SS
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression as LR
from sklearn.metrics import mean_squared_error as mse
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeRegressor
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [376]:
list=['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y']

In [377]:
data=pd.read_csv("D:/imarticus/bank.csv",sep=';',names=list,header=0)

In [378]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [379]:
data.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp_var_rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [380]:
data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp_var_rate      0
cons_price_idx    0
cons_conf_idx     0
euribor3m         0
nr_employed       0
y                 0
dtype: int64

In [381]:
data.age.unique()

array([56, 57, 37, 40, 45, 59, 41, 24, 25, 29, 35, 54, 46, 50, 39, 30, 55,
       49, 34, 52, 58, 32, 38, 44, 42, 60, 53, 47, 51, 48, 33, 31, 43, 36,
       28, 27, 26, 22, 23, 20, 21, 61, 19, 18, 70, 66, 76, 67, 73, 88, 95,
       77, 68, 75, 63, 80, 62, 65, 72, 82, 64, 71, 69, 78, 85, 79, 83, 81,
       74, 17, 87, 91, 86, 98, 94, 84, 92, 89], dtype=int64)

In [382]:
data.job.unique()

array(['housemaid', 'services', 'admin.', 'blue-collar', 'technician',
       'retired', 'management', 'unemployed', 'self-employed', 'unknown',
       'entrepreneur', 'student'], dtype=object)

In [383]:
data.marital.unique()

array(['married', 'single', 'divorced', 'unknown'], dtype=object)

In [384]:
data.education.unique()

array(['basic.4y', 'high.school', 'basic.6y', 'basic.9y',
       'professional.course', 'unknown', 'university.degree',
       'illiterate'], dtype=object)

In [385]:
data.default.unique()

array(['no', 'unknown', 'yes'], dtype=object)

In [386]:
data.housing.unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [387]:
data.loan.unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [388]:
data.contact.unique()

array(['telephone', 'cellular'], dtype=object)

In [389]:
data.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'mar', 'apr',
       'sep'], dtype=object)

In [390]:
data.day_of_week.unique()

array(['mon', 'tue', 'wed', 'thu', 'fri'], dtype=object)

In [391]:
data.duration.unique()

array([ 261,  149,  226, ..., 1246, 1556, 1868], dtype=int64)

In [392]:
data.campaign.unique()       


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 19, 18, 23, 14,
       22, 25, 16, 17, 15, 20, 56, 39, 35, 42, 28, 26, 27, 32, 21, 24, 29,
       31, 30, 41, 37, 40, 33, 34, 43], dtype=int64)

In [393]:
data.pdays.unique()             


array([999,   6,   4,   3,   5,   1,   0,  10,   7,   8,   9,  11,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27,
        20], dtype=int64)

In [394]:
data.previous.unique()        


array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [395]:
data.poutcome.unique()         


array(['nonexistent', 'failure', 'success'], dtype=object)

In [396]:
data.emp_var_rate.unique()      


array([ 1.1,  1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3. , -1.7, -1.1])

In [397]:
data.cons_price_idx.unique()  


array([93.994, 94.465, 93.918, 93.444, 93.798, 93.2  , 92.756, 92.843,
       93.075, 92.893, 92.963, 92.469, 92.201, 92.379, 92.431, 92.649,
       92.713, 93.369, 93.749, 93.876, 94.055, 94.215, 94.027, 94.199,
       94.601, 94.767])

In [398]:
le = preprocessing.LabelEncoder()

In [399]:
data.job=le.fit_transform(data.job)

In [400]:
data.marital=le.fit_transform(data.marital)

In [401]:
data.education=le.fit_transform(data.education)

In [402]:
data.default=le.fit_transform(data.default)

In [403]:
data.housing=le.fit_transform(data.housing)

In [404]:
data.loan=le.fit_transform(data.loan)

In [405]:
data.contact=le.fit_transform(data.contact)

In [406]:
data.month=le.fit_transform(data.month)

In [407]:
data.day_of_week=le.fit_transform(data.day_of_week)

In [408]:
data.poutcome=le.fit_transform(data.poutcome)

In [409]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  int32  
 2   marital         41188 non-null  int32  
 3   education       41188 non-null  int32  
 4   default         41188 non-null  int32  
 5   housing         41188 non-null  int32  
 6   loan            41188 non-null  int32  
 7   contact         41188 non-null  int32  
 8   month           41188 non-null  int32  
 9   day_of_week     41188 non-null  int32  
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  int32  
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null 

In [410]:
Y=data.y

In [411]:
Y=le.fit_transform(Y)

In [412]:
Y

array([0, 0, 0, ..., 0, 1, 0])

In [413]:
X=data.drop('y',axis=1)

In [414]:
X.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   56    3        1          0        0        0     0        1      6   
1   57    7        1          3        1        0     0        1      6   
2   37    7        1          3        0        2     0        1      6   
3   40    0        1          1        0        0     0        1      6   
4   56    7        1          3        0        0     2        1      6   

   day_of_week  duration  campaign  pdays  previous  poutcome  emp_var_rate  \
0            1       261         1    999         0         1           1.1   
1            1       149         1    999         0         1           1.1   
2            1       226         1    999         0         1           1.1   
3            1       151         1    999         0         1           1.1   
4            1       307         1    999         0         1           1.1   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed  
0          93.994          -36.4      4.857       5191.0  
1          93.994          -36.4      4.857       5191.0  
2          93.994          -36.4      4.857       5191.0  
3          93.994          -36.4      4.857       5191.0  
4          93.994          -36.4      4.857       5191.0

In [415]:
scalar=SS()

In [416]:
scaledX=scalar.fit_transform(X)

In [417]:
scaledX=pd.DataFrame(scaledX)

In [418]:
scaledX.columns=X.columns

In [419]:
scaledX.head()

age       job   marital  education   default   housing      loan  \
0  1.533034 -0.201579 -0.283741  -1.753925 -0.513600 -1.087707 -0.452491   
1  1.628993  0.911227 -0.283741  -0.349730  1.945327 -1.087707 -0.452491   
2 -0.290186  0.911227 -0.283741  -0.349730 -0.513600  0.942127 -0.452491   
3 -0.002309 -1.036184 -0.283741  -1.285860 -0.513600 -1.087707 -0.452491   
4  1.533034  0.911227 -0.283741  -0.349730 -0.513600 -1.087707  2.311440   

   contact     month  day_of_week  duration  campaign     pdays  previous  \
0  1.31827  0.762558    -0.718834  0.010471 -0.565922  0.195414 -0.349494   
1  1.31827  0.762558    -0.718834 -0.421501 -0.565922  0.195414 -0.349494   
2  1.31827  0.762558    -0.718834 -0.124520 -0.565922  0.195414 -0.349494   
3  1.31827  0.762558    -0.718834 -0.413787 -0.565922  0.195414 -0.349494   
4  1.31827  0.762558    -0.718834  0.187888 -0.565922  0.195414 -0.349494   

   poutcome  emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  \
0  0.192622      0.648092        0.722722       0.886447    0.71246   
1  0.192622      0.648092        0.722722       0.886447    0.71246   
2  0.192622      0.648092        0.722722       0.886447    0.71246   
3  0.192622      0.648092        0.722722       0.886447    0.71246   
4  0.192622      0.648092        0.722722       0.886447    0.71246   

   nr_employed  
0      0.33168  
1      0.33168  
2      0.33168  
3      0.33168  
4      0.33168

In [420]:
xtrain,xtest,ytrain,ytest = train_test_split(scaledX,Y,test_size=0.3,random_state=100)

In [421]:
xtrain.shape

(28831, 20)

In [422]:
ytrain.shape

(28831,)

In [423]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [424]:
sel = SelectFromModel(RandomForestClassifier(n_estimators = 100))
sel.fit(xtrain, ytrain)

SelectFromModel(estimator=RandomForestClassifier())

In [425]:
selected_feat= xtrain.columns[(sel.get_support())]
len(selected_feat)

4

In [426]:
selected_feat

Index(['age', 'duration', 'euribor3m', 'nr_employed'], dtype='object')

In [432]:
Selected=scaledX[['age', 'duration', 'euribor3m', 'nr_employed']]

In [433]:
Selected.head()

age  duration  euribor3m  nr_employed
0  1.533034  0.010471    0.71246      0.33168
1  1.628993 -0.421501    0.71246      0.33168
2 -0.290186 -0.124520    0.71246      0.33168
3 -0.002309 -0.413787    0.71246      0.33168
4  1.533034  0.187888    0.71246      0.33168

<h6>
models
<h6>

<h6> logistical<h6>

In [436]:
x_train,x_test,y_train,y_test = train_test_split(Selected,Y,test_size=0.3,random_state=100)

In [437]:
modellr=LR()

In [439]:
modellr.fit(x_train,y_train)

LogisticRegression()

In [442]:
predicted_y=modellr.predict(x_test)

In [444]:
modellr.score(x_train,y_train)

0.9030210537268912

In [445]:
modellr.score(x_test,predicted_y)

1.0

In [447]:
finallr=modellr.fit(Selected,Y)

In [448]:
finallr.score(Selected,Y)

0.9034913081480043

<h6>
adaboost
<h6>

In [449]:
from sklearn.ensemble import AdaBoostRegressor
regress=AdaBoostRegressor(random_state=0, n_estimators=100)
regress.fit(x_train, y_train)

AdaBoostRegressor(n_estimators=100, random_state=0)

In [450]:
regress.score(x_train,y_train)

0.1527022858223097

In [451]:
regress.score(x_test,y_test)

0.14734176279091904

<h6>
naive bayes
<h6>

In [453]:
gnb = GaussianNB()

In [454]:
gnb.fit(x_train, y_train)

GaussianNB()

In [455]:
 y_pred = gnb.predict(x_test)

In [456]:
metrics.accuracy_score(y_test,y_pred)

0.889698146799385

In [457]:
modelf=gnb.fit(Selected,Y)

In [458]:
 y_predf = gnb.predict(Selected)

In [460]:
metrics.accuracy_score(Y,y_predf)

0.8890939108478197

In [462]:
from sklearn import svm
clf = svm.SVC(kernel='linear') 
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
clf.score(x_test,y_test)
clf.fit(Selected,Y)
clf.score(Selected,Y)

0.8949451296494124

<h6>
knn
<h6>

In [466]:
from sklearn.neighbors import KNeighborsClassifier
score1=[]
for i in range(1,15):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train, y_train)
    y_predict = model.predict(x_test)
    score1.append(model.score(x_test,y_test))


In [467]:
print(score1)

[0.8857327830379542, 0.8953629521728574, 0.8981144290685441, 0.9011896091284293, 0.9015942380836772, 0.9017560896657765, 0.9040220118151655, 0.902889050740471, 0.9032127539046694, 0.9041029376062151, 0.90515497288986, 0.9045884923525127, 0.9053168244719592, 0.9068544145019017]


In [468]:
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train, y_train)    
y_predict = model.predict(x_test)
model.score(x_test,y_test)

0.9068544145019017